Repository cashubtc/nuts, pull requests merged in 2024-06, with the labels that each got.

#117 NUT-6: update contact info
  06.md
Labels: breaking change, ready, needs implementation, new nut

#98 NUT-17: WebSocket state updates
  17.md
Labels: ready, new nut

#126 Add fees to NUT-02
  02.md
  README.md
Labels: breaking change, ready
